name: Deploy Lambda Function

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Zip Lambda code
        run: zip -r function.zip app/src app/requirements.txt

      - name: Upload Lambda ZIP to S3
        run: aws s3 cp function.zip s3://$LAMBDA_BUCKET/function.zip
        env:
          LAMBDA_BUCKET: ${{ secrets.LAMBDA_BUCKET }}

      - name: Update Lambda function code
        run: |
          aws lambda update-function-code \
            --function-name GetDataIoTLambda \
            --s3-bucket $LAMBDA_BUCKET \
            --s3-key function.zip \
            --region us-east-1
        env:
          LAMBDA_BUCKET: ${{ secrets.LAMBDA_BUCKET }}
