name: "Develop DEPLOY"

on:
  push:
    branches:
      - develop

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: "./.github/workflows/terraform.yml"
    with:
      environment: dev
      aws-assume-role: ""
      aws-s3-bucket: "dev-us-east-1-iot-twinmaker"
      aws-timestream-database: "dev-timestream-db"
      aws-region: "us-east-1"